server:
  port: 7002
spring:
  application:
    name: orthopaedics-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
